// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetBatteryStatus():Promise<string>;

export function GetConfig():Promise<main.AppConfig>;

export function SaveConfig(arg1:main.AppConfig):Promise<void>;
